### ISSUE TITLE
Change soldier rank gating to allow more than Sergeants + possibly make it on difficulty basis

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#6]
In base LWOTC, soldiers are pretty much stuck being sergeants for almost the entire campaign from BM/other rewards and by the time its FL 19... not sure how much staff sergeants will help you if you are still alive.

XcomGameData.Ini is the source of this
This is base LWOTC:
```
!SoldierRewardForceLevelGates=()
+SoldierRewardForceLevelGates=2;			LCPL (3 weeks)
+SoldierRewardForceLevelGates=4;			CPL  (9 weeks)
+SoldierRewardForceLevelGates=9;			SGT
+SoldierRewardForceLevelGates=19;		SSGT
+SoldierRewardForceLevelGates=9999;		TSGT
+SoldierRewardForceLevelGates=9999;		GSGT
+SoldierRewardForceLevelGates=9999;		MSGT

```

This is how Mod Jam has it
```
[XComGame.X2StrategyElement_DefaultRewards]

!SoldierRewardForceLevelGates=()
+SoldierRewardForceLevelGates=2;            LCPL (3 weeks)
+SoldierRewardForceLevelGates=4;            CPL  (9 weeks)
+SoldierRewardForceLevelGates=6;            SGT
+SoldierRewardForceLevelGates=10;       SSGT
+SoldierRewardForceLevelGates=16;       TSGT
+SoldierRewardForceLevelGates=9999;     GSGT
+SoldierRewardForceLevelGates=9999;     MSGT
```

You also thought of making difficulty adjust these, so if you feel lucky and brave enough, go ahead.

**Comment by Tedster59** [comment]
turns out MJ swapped to the following so I've updated to this as well:

!SoldierRewardForceLevelGates=()
+SoldierRewardForceLevelGates=2;		LCPL 
+SoldierRewardForceLevelGates=4;		CPL  
+SoldierRewardForceLevelGates=9;		SGT
+SoldierRewardForceLevelGates=15;		SSGT
+SoldierRewardForceLevelGates=20;		TSGT
+SoldierRewardForceLevelGates=35;		GSGT
+SoldierRewardForceLevelGates=40;		MSGT
