### ISSUE TITLE
Proximity mines can miss, time to fix them

### ISSUE THREAD

**Issue by Mrveczt** [Tedster59/lwotc#7]
Look, this is above me and how this actually works might be outside of simple ini edits, so here are some leads you might want to dig out, i am just making a post here so it doesnt get burried till its resolved.

![image](https://github.com/Tedster59/lwotc/assets/134306115/f0597d3c-b5ba-445f-9b6c-93fb2f7121a1)

Link to the convo
https://discord.com/channels/590853492084572170/891335947415867412/1081545236238577805

**Comment by Tedster59** [comment]
Looking at the base game code, the bIndirectFire flag should add 100 to aim for the indirect attack, just like the bGuaranteedHit flag.

![image](https://github.com/Tedster59/lwotc/assets/21696818/06ec8a5b-7ccc-44c3-8bf9-b30c734b4581)

Since we don't have guaranteed hit set, it should just hit the super.AddModifier anyways inside X2AbilityuToHitCalc_StandardAim

![image](https://github.com/Tedster59/lwotc/assets/21696818/99c98488-c239-469f-a288-338e2921a990)

**Comment by Tedster59** [comment]
Highlander fix for this is coming in 1.26.
